### ISSUE TITLE
DEV-Suitable error message for delete deployment when deployment not found

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1245]
On trying to delete an already deleted deployment the suitable delete failed message or "no deployment with the given name found" should be displayed.
The current response is as follows:

```
shrividyahegde@Shrividyas-MacBook-Pro test_dep % ./astro deployment delete
Current Workspace: testws

Please specify a name for your Deployment

Deployment name: testgcp
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x140 pc=0x10190ccb4]

goroutine 1 [running]:
github.com/astronomer/astro-cli/cloud/organization.ListClusters({0x140000456c8, 0x17}, {0x0, 0x0})
	/Users/kushal/Documents/astronomer/cli/src/github.com/astronomer/astro-cli/cloud/organization/organization.go:203 +0x104
github.com/astronomer/astro-cli/cloud/deployment.selectCluster({0x0, 0x0}, {0x140000456c8, 0x17}, {0x0, 0x0})
	/Users/kushal/Documents/astronomer/cli/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:463 +0x12c
github.com/astronomer/astro-cli/cloud/deployment.useSharedClusterOrSelectDedicatedCluster({0x0?, 0x1a?}, {0x0?, 0x1?}, {0x140000456c8?, 0x140001a2050?}, {0x0?, 0x4?}, {0x0?, 0x0?})
	/Users/kushal/Documents/astronomer/cli/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:535 +0x78
github.com/astronomer/astro-cli/cloud/deployment.Create({0x0, 0x0}, {0x140005801c0, 0x19}, {0x0, 0x0}, {0x0, 0x0}, {0x140001f8cc8, 0x5}, ...)
	/Users/kushal/Documents/astronomer/cli/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:249 +0x6a8
github.com/astronomer/astro-cli/cloud/deployment.deploymentSelectionProcess({_, _}, {_, _, _}, {_, _}, {_, _})
	/Users/kushal/Documents/astronomer/cli/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:900 +0x260
github.com/astronomer/astro-cli/cloud/deployment.GetDeployment({_, _}, {_, _}, {_, _}, {_, _}, {_, _})
	/Users/kushal/Documents/astronomer/cli/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:864 +0x218
github.com/astronomer/astro-cli/cloud/deployment.Delete({0x0?, 0x0?}, {0x140005801c0?, 0x0?}, {0x0?, 0x0?}, 0x0, {0x101f3e5b8, 0x140001a2050})
	/Users/kushal/Documents/astronomer/cli/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:727 +0x7c
github.com/astronomer/astro-cli/cmd/cloud.deploymentDelete(0x14000460300, {0x102849780, 0x0, 0x0?})
	/Users/kushal/Documents/astronomer/cli/src/github.com/astronomer/astro-cli/cmd/cloud/deployment.go:450 +0xe0
github.com/spf13/cobra.(*Command).execute(0x14000460300, {0x102849780, 0x0, 0x0})
	/Users/kushal/Documents/astronomer/cli/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x14000454000)
	/Users/kushal/Documents/astronomer/cli/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/kushal/Documents/astronomer/cli/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/Users/kushal/Documents/astronomer/cli/src/github.com/astronomer/astro-cli/main.go:16 +0x34
```

**What CLI Version did you experience this bug?**

Astro CLI Version: SNAPSHOT-b2c8f859

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro

**What Operating System is the above CLI installed on?**
Apple M1 Pro

**Comment by shri-astro** [comment]
```
shrividyahegde@Shrividyas-MacBook-Pro ~ % astro deployment delete
Select a Deployment
 #     DEPLOYMENT NAME            RELEASE NAME                     DEPLOYMENT ID                 DAG DEPLOY ENABLED     
 1     gcptest_dedicated          elementary-quasar-1502           cliwzsgfi39921iz19oy09eyi     true                   
 2     only dedicated as flag     energetic-constellation-8224     cliwzt3dp49391iyyuww8co0c     false                  

> 1

Are you sure you want to delete the gcptest_dedicated Deployment? (y/n) y

Successfully deleted deployment gcptest_dedicated
shrividyahegde@Shrividyas-MacBook-Pro ~ % astro deployment delete
^[[AOnly one Deployment was found. Using the following Deployment by default: 

 Deployment Name: only dedicated as flag
 Deployment ID: cliwzt3dp49391iyyuww8co0c


Are you sure you want to delete the only dedicated as flag Deployment? (y/n) ^R
y  

Successfully deleted deployment only dedicated as flag
shrividyahegde@Shrividyas-MacBook-Pro ~ % astro deployment delete
No Deployments found in workspace cliuda3f9004h01kgshi5lci3 to delete
```
