### ISSUE TITLE
DEV-Suitable error message for deployment not found error in case of worker queue update

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1283]
The following command was run when there were no existing deployments and the below mentioned error message was received.
A suitable error message indicating the deployment creation or missing deployment to be displayed.

Command:
```
./astro deployment worker-queue update --concurrency 30
```
Error message:
```
shrividyahegde@Shrividyas-MacBook-Pro test_dep % ./astro deployment worker-queue update --concurrency 30
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x248 pc=0x1c8e8fe]

goroutine 1 [running]:
github.com/astronomer/astro-cli/cloud/workspace.GetWorkspaces({0x0, 0x0})
	/Users/shrividyahegde/Documents/Github/astro-cli/cloud/workspace/workspace.go:382 +0x1de
github.com/astronomer/astro-cli/cloud/deployment.Create({0x0, 0x0}, {0xc000501ae0, 0x19}, {0x0, 0x0}, {0x0, _}, {0xc000474dc8, 0x5}, ...)
	/Users/shrividyahegde/Documents/Github/astro-cli/cloud/deployment/deployment.go:210 +0x291
github.com/astronomer/astro-cli/cloud/deployment.deploymentSelectionProcess({_, _}, {_, _, _}, {_, _}, {_, _})
	/Users/shrividyahegde/Documents/Github/astro-cli/cloud/deployment/deployment.go:915 +0x3b4
github.com/astronomer/astro-cli/cloud/deployment.GetDeployment({_, _}, {_, _}, {_, _}, _, {_, _}, {0x0, ...})
	/Users/shrividyahegde/Documents/Github/astro-cli/cloud/deployment/deployment.go:879 +0x371
github.com/astronomer/astro-cli/cloud/deployment/workerqueue.CreateOrUpdate({0xc000501ae0, 0x19}, {0x0?, 0x0?}, {0x0?, 0x0?}, {0x0, 0x0}, {0x20a2626, 0x6}, ...)
	/Users/shrividyahegde/Documents/Github/astro-cli/cloud/deployment/workerqueue/workerqueue.go:51 +0x133
github.com/astronomer/astro-cli/cmd/cloud.deploymentWorkerQueueCreateOrUpdate(0xc00031a300, {0x0?, 0x0?, 0x0?}, {0x22deda0, 0xc000010018})
	/Users/shrividyahegde/Documents/Github/astro-cli/cmd/cloud/deployment_workerqueue.go:103 +0x17b
github.com/astronomer/astro-cli/cmd/cloud.newDeploymentWorkerQueueUpdateCmd.func1(0xc00031a300?, {0xc00013d740?, 0x2?, 0x2?})
	/Users/shrividyahegde/Documents/Github/astro-cli/cmd/cloud/deployment_workerqueue.go:63 +0x26
github.com/spf13/cobra.(*Command).execute(0xc00031a300, {0xc00013d720, 0x2, 0x2})
	/Users/shrividyahegde/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc00030a000)
	/Users/shrividyahegde/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/shrividyahegde/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/Users/shrividyahegde/Documents/Github/astro-cli/main.go:16 +0x31
```

**What CLI Version did you experience this bug?**
Latest code built from main

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro

**What Operating System is the above CLI installed on?**
Apple M1 Pro

**Comment by shri-astro** [comment]
Resolved
```
shrividyahegde@Shrividyas-MacBook-Pro test_dep % ./astro deployment worker-queue update --concurrency 30
No Deployments found in workspace cljie9pp6001y01p8vis2fu1j
```
