### ISSUE TITLE
DEV- User is able to update the worker type for Kubernetes deployment

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1348]
Kubernetes deployments under the hood use a5 type and there is no provision for the user to update the worker type of a KE default queue through UI.
However on trying to update the worker type of the KE deployment through CLI commands, the operation is successful.

```
shrividyahegde@Shrividyas-MacBook-Pro ~ % astro deployment worker-queue update default -d cll3hk62s1434731uymoywi92rr -t a10 

 #     WORKER QUEUE     ISDEFAULT     ID                              
 1     default          true          cll3k0myx2059731b1jtvsy58ls     

> 1

Are you sure you want to update the default worker queue? If there are any tasks in your DAGs assigned to this worker queue, the tasks might get stuck in a queued state and fail to execute (y/n) y
worker queue default for Kubernetes_shared in clkmpjzfk002d01m8vnpg1tu7 workspace updated
shrividyahegde@Shrividyas-MacBook-Pro ~ % astro deployment inspect                                                                           
Select a Deployment
 #     DEPLOYMENT NAME       RELEASE NAME                DEPLOYMENT ID                   DAG DEPLOY ENABLED     
 1     Kubernetes_shared     popular-rotation-3223       cll3hk62s1434731uymoywi92rr     false                  
 2     CE dedicated          prehistoric-axis-6302       cll3k5e1q2064611b1jkfis8z2a     false                  
 3     CE shared             siderean-supernova-8319     cll3k8j5n2039971u1unnf93h2r     false                  

> 1
deployment:
    configuration:
        name: Kubernetes_shared
        description: ""
        runtime_version: 8.8.0
        dag_deploy_enabled: false
        ci_cd_enforcement: true
        scheduler_size: small
        is_high_availability: false
        executor: KubernetesExecutor
        scheduler_au: 10
        scheduler_count: 1
        cluster_name: us-east4
        workspace_name: Astro_hosted_CLI_Automation_Restricted_Workspace
        deployment_type: HOSTED_SHARED
        cloud_provider: gcp
        region: us-east4
    worker_queues:
        - name: default
          worker_type: a10
          pod_cpu: "0.25"
          pod_ram: 0.5Gi
    metadata:
        deployment_id: cll3hk62s1434731uymoywi92rr
        workspace_id: clkmpjzfk002d01m8vnpg1tu7
        cluster_id: us-east4
        release_name: N/A
        airflow_version: 2.6.3
        current_tag: 8.8.0
        status: HEALTHY
        created_at: 2023-08-09T08:46:08.068Z
        updated_at: 2023-08-09T13:19:52.49Z
        deployment_url: cloud.astronomer-dev.io/clkmpjzfk002d01m8vnpg1tu7/deployments/cll3hk62s1434731uymoywi92rr/analytics
        webserver_url: org-shri-hosted-dedicated-1.astronomer-dev.run/dywi92rr
        workload_identity: astro-popular-rotation-3223@astro-dev-us-east4-0001.iam.gserviceaccount.com

shrividyahegde@Shrividyas-MacBook-Pro ~ % 

```

**What CLI Version did you experience this bug?**
1.18.1

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro

**🪜 Steps To Reproduce**
1.Create a KE deployment
2.Update the worker type of the deployment using the command mentioned above to change it from a5 to a10

**Comment by shri-astro** [comment]
Also seen in the latest prerelease version

**Comment by shri-astro** [comment]
The following error is seen in the latest pre-release version:
```
shrividyahegde@Hegde sample1 % astro deployment worker-queue update default -t A5
Only one Deployment was found. Using the following Deployment by default: 

 Deployment Name: t
 Deployment ID: cls4pyg4g000801nin0ks5s14

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x101a9550c]

goroutine 1 [running]:
github.com/astronomer/astro-cli/cloud/deployment/workerqueue.selectQueue(0x0?, {0x10209d9e0, 0x1400019e008})
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/workerqueue/workerqueue.go:609 +0x3c
github.com/astronomer/astro-cli/cloud/deployment/workerqueue.getQueueName({0x0?, 0x2?}, {0x101aede44?, 0x5?}, 0x2?, {0x10209d9e0?, 0x1400019e008?})
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/workerqueue/workerqueue.go:725 +0xac
github.com/astronomer/astro-cli/cloud/deployment/workerqueue.CreateOrUpdate({0x1400010cc80, 0x19}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x101aede44, 0x6}, ...)
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/workerqueue/workerqueue.go:111 +0x15e0
github.com/astronomer/astro-cli/cmd/cloud.deploymentWorkerQueueCreateOrUpdate(0x1400015cf00, {0x0?, 0x0?, 0x0?}, {0x10209d9e0, 0x1400019e008})
	/go/src/github.com/astronomer/astro-cli/cmd/cloud/deployment_workerqueue.go:109 +0x16c
github.com/astronomer/astro-cli/cmd/cloud.newDeploymentWorkerQueueUpdateCmd.func1(0x1400015cf00?, {0x140002106c0?, 0x3?, 0x3?})
	/go/src/github.com/astronomer/astro-cli/cmd/cloud/deployment_workerqueue.go:65 +0x28
github.com/spf13/cobra.(*Command).execute(0x1400015cf00, {0x14000210660, 0x3, 0x3})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x14000026900)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/go/src/github.com/astronomer/astro-cli/main.go:16 +0x34
	```

**Comment by shri-astro** [comment]
Resolved:
```

shrividyahegde@Hegde testlimits % astro deployment worker-queue update default -t A5
Select a Deployment
 #     DEPLOYMENT NAME     RELEASE NAME                 DEPLOYMENT ID                 DAG DEPLOY ENABLED     
 1     1                   celestial-telemetry-6744     clssx86yo0bvr01oojmn9wigu     true                   

> 1

 #     WORKER QUEUE     ISDEFAULT     ID                            
 1     default          true          clssx872g0bvx01oode2df2xk     

> 1

Are you sure you want to update the default worker queue? If there are any tasks in your DAGs assigned to this worker queue, the tasks might get stuck in a queued state and fail to execute (y/n) y
worker queue default for 1 in cls8pqheo00i301pcq8x7bi1z workspace updated
```
