### ISSUE TITLE
DEV - Panic error on updating the scheuduler size for workspace with no deployments

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1504]
The command ```astro deployment update --scheduler-size medium```  is used to update the scheduler size.
When no deployments were present the above command was issued.
Instead of "No deployments found in this worksapce" the following errors were seen:

For the latest CLI version the following error is seen.

```
shrividyahegde@Hegde ~ % astro deployment update --scheduler-size medium
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x1b8 pc=0x1029684b4]

goroutine 1 [running]:
github.com/astronomer/astro-cli/cloud/deployment.glob..func7({_, _}, {_, _, _, _}, {_, _})
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:1316 +0x124
github.com/astronomer/astro-cli/cloud/deployment.Create({0x0, 0x0}, {0x140005455c0, 0x19}, {0x0, _}, {_, _}, {_, _}, ...)
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:243 +0x330
github.com/astronomer/astro-cli/cloud/deployment.deploymentSelectionProcess({_, _}, {_, _, _}, {_, _}, {_, _})
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:1493 +0x1dc
github.com/astronomer/astro-cli/cloud/deployment.GetDeployment({_, _}, {_, _}, {_, _}, _, {_, _}, {_, ...})
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:1457 +0x1e8
github.com/astronomer/astro-cli/cloud/deployment.Update({0x0, 0x0}, {_, _}, {_, _}, {_, _}, {_, _}, ...)
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:717 +0x108
github.com/astronomer/astro-cli/cmd/cloud.deploymentUpdate(0x14000397800, {0x14000366620, 0x0, 0x0?}, {0x1035319e0, 0x1400019e008})
	/go/src/github.com/astronomer/astro-cli/cmd/cloud/deployment.go:491 +0x88c
github.com/astronomer/astro-cli/cmd/cloud.newDeploymentUpdateCmd.func1(0x14000397800?, {0x14000366620?, 0x2?, 0x2?})
	/go/src/github.com/astronomer/astro-cli/cmd/cloud/deployment.go:193 +0x28
github.com/spf13/cobra.(*Command).execute(0x14000397800, {0x14000366600, 0x2, 0x2})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x1400002c900)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/go/src/github.com/astronomer/astro-cli/main.go:16 +0x34
	```
**What CLI Version did you experience this bug?**
v2.0.0

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro

**What Operating System is the above CLI installed on?**
Mac M1 Pro

**Comment by shri-astro** [comment]
same error for the deployment update command 
```
shrividyahegde@Hegde ~ % astro deployment update
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x1b8 pc=0x1014eb8a0]

goroutine 1 [running]:
github.com/astronomer/astro-cli/cloud/deployment.glob..func7({_, _}, {_, _, _, _}, {_, _})
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:1329 +0x120
github.com/astronomer/astro-cli/cloud/deployment.Create({0x0, 0x0}, {0x140004b3a40, 0x19}, {0x0, _}, {_, _}, {_, _}, ...)
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:222 +0x308
github.com/astronomer/astro-cli/cloud/deployment.deploymentSelectionProcess({_, _}, {_, _, _}, {_, _}, {_, _})
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:1506 +0x1ec
github.com/astronomer/astro-cli/cloud/deployment.GetDeployment({_, _}, {_, _}, {_, _}, _, {_, _}, {_, ...})
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:1470 +0x1dc
github.com/astronomer/astro-cli/cloud/deployment.Update({0x0, 0x0}, {_, _}, {_, _}, {_, _}, {_, _}, ...)
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:717 +0x104
github.com/astronomer/astro-cli/cmd/cloud.deploymentUpdate(0x14000473500, {0x102a1ef40, 0x0, 0x0?}, {0x10207cb58, 0x1400018a008})
	/go/src/github.com/astronomer/astro-cli/cmd/cloud/deployment.go:492 +0x730
github.com/astronomer/astro-cli/cmd/cloud.newDeploymentUpdateCmd.func1(0x14000208400?, {0x102a1ef40?, 0x4?, 0x101af6c57?})
	/go/src/github.com/astronomer/astro-cli/cmd/cloud/deployment.go:194 +0x28
github.com/spf13/cobra.(*Command).execute(0x14000473500, {0x102a1ef40, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x66c
github.com/spf13/cobra.(*Command).ExecuteC(0x1400026c600)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x320
github.com/spf13/cobra.(*Command).Execute(0x102094658?)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968 +0x1c
main.main()
	/go/src/github.com/astronomer/astro-cli/main.go:16 +0x38
shrividyahegde@Hegde ~ % astro deployment list
No Deployments found in workspace clkmpjzfk002d01m8vnpg1tu7
```

**Comment by shri-astro** [comment]
Instead of a message saying "No deployments found", a new deployment creation option is provided, when followed, there is an unrelated error
```
shrividyahegde@Hegde testlimits % astro deployment list                                                
no Deployments found in workspace cls8kdoks00bk01pcuus8lfhl
shrividyahegde@Hegde testlimits % astro deployment update --scheduler-size medium
Current Workspace: Automation CLI dev workspace

Please specify a name for your Deployment

Deployment name: test

Please select a Region for your Deployment:
 #     REGION         
 1     westeurope     
 2     westus2        
 3     eastus2        

> 2
Error: Invalid field values: field defaultTaskPodCpu failed check on isKubernetesResourceString;,field cloudProvider failed check on oneof; cloudProvider should be one of: AWS AZURE GCP;
shrividyahegde@Hegde testlimits % 
```

**Comment by kushalmalani** [comment]
@shri-astro This is intended flow. We do allow for deployment creation if you dont have one in the workspace. The error you are getting is being tracked as part of this ticket - https://github.com/astronomer/astro-cli/issues/1356

Going to close this ticket, so we can fix the issue as part of the other one
