### ISSUE TITLE
DEV-  Updating the resource quota fields using the deployment yaml file gives panic error

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1512]
The following was the response on attempting to update a deployment with the resource quota cpu value from 10 to 11 and memory value from 20GB to 22GB

```
shrividyahegde@Hegde ~ % astro deployment update --deployment-file deploy.yaml 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x10168588c]

goroutine 1 [running]:
github.com/astronomer/astro-cli/cloud/deployment/fromfile.getClusterInfoFromName({0x1400011bbf0, 0x2c}, {0x14000581aa0?, 0x19?}, {0x101ca1998?, 0x140002e9da0?})
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/fromfile/fromfile.go:675 +0x18c
github.com/astronomer/astro-cli/cloud/deployment/fromfile.CreateOrUpdate({0x16f3e79d2, 0xb}, {0x1016ec964, 0x6}, {0x101ca1998, 0x140002e9da0}, {0x101ca7920, 0x140002e9d90}, {0x101c859e0, 0x1400019e008})
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/fromfile/fromfile.go:96 +0x244
github.com/astronomer/astro-cli/cmd/cloud.deploymentUpdate(0x140003c9800, {0x140003fa2a0, 0x0, 0x0?}, {0x101c859e0, 0x1400019e008})
	/go/src/github.com/astronomer/astro-cli/cmd/cloud/deployment.go:459 +0x944
github.com/astronomer/astro-cli/cmd/cloud.newDeploymentUpdateCmd.func1(0x140003c9800?, {0x140003fa2a0?, 0x2?, 0x2?})
	/go/src/github.com/astronomer/astro-cli/cmd/cloud/deployment.go:193 +0x28
github.com/spf13/cobra.(*Command).execute(0x140003c9800, {0x140003fa280, 0x2, 0x2})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x140000a0900)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/go/src/github.com/astronomer/astro-cli/main.go:16 +0x34
shrividyahegde@Hegde ~ % cat deploy.yaml                                      
deployment:
    configuration:
        name: test
        description: ""
        runtime_version: 10.2.0
        dag_deploy_enabled: false
        ci_cd_enforcement: false
        scheduler_size: SMALL
        is_high_availability: false
        executor: CELERY
        scheduler_au: 0
        scheduler_count: 1
        cluster_name: Dedicated cluster for testing13:55:52.157504
        workspace_name: Astro_hosted_CLI_Automation_Restricted_Workspace
        deployment_type: DEDICATED
        cloud_provider: gcp
        region: ""
        default_task_pod_cpu: "0.25"
        default_task_pod_memory: 0.5Gi
        resource_quota_cpu: "11"
        resource_quota_memory: 22Gi
    worker_queues:
        - name: default
          max_worker_count: 10
          worker_concurrency: 5
          worker_type: A5
shrividyahegde@Hegde ~ % 

```

**What CLI Version did you experience this bug?**
v2.0.0

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro

**What Operating System is the above CLI installed on?**
Mac M1 Pro

**Comment by shri-astro** [comment]
Resolved
