### ISSUE TITLE
DEV- Negative scenario to update the min max count for the worker queue gives panic error

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1527]
The panic response is seen for the following command
```
shrividyahegde@Hegde ~ % astro deployment worker-queue update default --min-count 10 --max-count 1 -d cls8pb3si00d301mljxzmeory -t A40
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1038e1d10]

goroutine 1 [running]:
github.com/astronomer/astro-cli/cloud/deployment/workerqueue.selectQueue(0x0?, {0x103ebcb58, 0x14000072028})
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/workerqueue/workerqueue.go:609 +0x40
github.com/astronomer/astro-cli/cloud/deployment/workerqueue.getQueueName({0x0?, 0x3?}, {0x103938b21?, 0x5?}, 0x2?, {0x103ebcb58?, 0x14000072028?})
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/workerqueue/workerqueue.go:725 +0x9c
github.com/astronomer/astro-cli/cloud/deployment/workerqueue.CreateOrUpdate({0x1400050d420, 0x19}, {0x16d1779bd, 0x19}, {0x0, 0x0}, {0x0, 0x0}, {0x103938b21, 0x6}, ...)
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/workerqueue/workerqueue.go:111 +0x16b8
github.com/astronomer/astro-cli/cmd/cloud.deploymentWorkerQueueCreateOrUpdate(0x1400056cc00, {0x0?, 0x0?, 0x0?}, {0x103ebcb58, 0x14000072028})
	/go/src/github.com/astronomer/astro-cli/cmd/cloud/deployment_workerqueue.go:109 +0x150
github.com/astronomer/astro-cli/cmd/cloud.newDeploymentWorkerQueueUpdateCmd.func1(0x140002d0a00?, {0x140000f2ab0?, 0x4?, 0x103936c57?})
	/go/src/github.com/astronomer/astro-cli/cmd/cloud/deployment_workerqueue.go:65 +0x28
github.com/spf13/cobra.(*Command).execute(0x1400056cc00, {0x140000f2a20, 0x9, 0x9})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x66c
github.com/spf13/cobra.(*Command).ExecuteC(0x140001d4300)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x320
github.com/spf13/cobra.(*Command).Execute(0x103ed4658?)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968 +0x1c
main.main()
	/go/src/github.com/astronomer/astro-cli/main.go:16 +0x38
	
```

**What CLI Version did you experience this bug?**
1.23.0

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro

**What Operating System is the above CLI installed on?**
Mac M1 Pro

**Comment by shri-astro** [comment]
Resolved:
```
shrividyahegde@Hegde testlimits % astro deployment worker-queue update default --min-count 10 --max-count 1 -d cltcuxxua0dkb01jz4umnhro5 -t A40

 #     WORKER QUEUE      ISDEFAULT     ID                            
 1     additionalwq      false         cltcuxxyo0dkh01jzvx26bl20     
 2     additionalwqq     false         cltcwtxsf0d6v01jls5bmz6be     
 3     default           true          cltcwt9qo0cvw01jxwhd9x1l4     

> 1

Are you sure you want to update the additionalwq worker queue? If there are any tasks in your DAGs assigned to this worker queue, the tasks might get stuck in a queued state and fail to execute (y/n) y
Error: Invalid request: minimum worker count cannot exceed maximum worker count 1, requested 10

```
