### ISSUE TITLE
DEV- Deployment pool list and create displays panic errors

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1542]
Commands used:
```
astro deployment pool list
astro deployment pool create
```

Results
```
shrividyahegde@Hegde ~ % astro deployment pool list
Only one Deployment was found. Using the following Deployment by default: 

 Deployment Name: cli_auto_with_multiple_dag_only_deploys_in_a_minute
 Deployment ID: clsiy2it901uz01i6npxefln2

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x105ad81b8]

goroutine 1 [running]:
github.com/astronomer/astro-cli/cloud/deployment/inspect.ReturnSpecifiedValue({0x14000047ee0?, 0x0?}, {0x0?, 0x0?}, {0x0?, 0x0?}, {0x1060d8c48, 0x140003857b0}, {0x1060de3f0?, 0x140003857a0?}, ...)
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/inspect/inspect.go:288 +0x178
github.com/astronomer/astro-cli/cmd/cloud.deploymentPoolList(0x14000697800, {0x1060b8b58, 0x1400018a008})
	/go/src/github.com/astronomer/astro-cli/cmd/cloud/deployment_objects.go:571 +0xb4
github.com/astronomer/astro-cli/cmd/cloud.newDeploymentPoolListCmd.func1(0x14000209400?, {0x105b32c53?, 0x4?, 0x105b32c57?})
	/go/src/github.com/astronomer/astro-cli/cmd/cloud/deployment_objects.go:256 +0x24
github.com/spf13/cobra.(*Command).execute(0x14000697800, {0x106a5af40, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x66c
github.com/spf13/cobra.(*Command).ExecuteC(0x140002e4300)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x320
github.com/spf13/cobra.(*Command).Execute(0x1060d0658?)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968 +0x1c
main.main()
	/go/src/github.com/astronomer/astro-cli/main.go:16 +0x38
shrividyahegde@Hegde ~ % astro deployment pool create
Only one Deployment was found. Using the following Deployment by default: 

 Deployment Name: cli_auto_with_multiple_dag_only_deploys_in_a_minute
 Deployment ID: clsiy2it901uz01i6npxefln2

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104d141b8]

goroutine 1 [running]:
github.com/astronomer/astro-cli/cloud/deployment/inspect.ReturnSpecifiedValue({0x1400050c700?, 0x0?}, {0x0?, 0x0?}, {0x0?, 0x0?}, {0x105314c48, 0x140002478b0}, {0x10531a3f0?, 0x140002478a0?}, ...)
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/inspect/inspect.go:288 +0x178
github.com/astronomer/astro-cli/cmd/cloud.deploymentPoolCreate(0x14000167b00, {0x1052f4b58, 0x14000072028})
	/go/src/github.com/astronomer/astro-cli/cmd/cloud/deployment_objects.go:593 +0xb8
github.com/astronomer/astro-cli/cmd/cloud.newDeploymentPoolCreateCmd.func1(0x140002cd800?, {0x104d6ec53?, 0x4?, 0x104d6ec57?})
	/go/src/github.com/astronomer/astro-cli/cmd/cloud/deployment_objects.go:273 +0x24
github.com/spf13/cobra.(*Command).execute(0x14000167b00, {0x105c96f40, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x66c
github.com/spf13/cobra.(*Command).ExecuteC(0x140001dc600)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x320
github.com/spf13/cobra.(*Command).Execute(0x10530c658?)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968 +0x1c
main.main()
	/go/src/github.com/astronomer/astro-cli/main.go:16 +0x38
```

**What CLI Version did you experience this bug?**

1.23.0

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro

**What Operating System is the above CLI installed on?**
Mac M1 Pro

**Comment by sunkickr** [comment]
not able to reproduce. Was this on prod or dev?
