### ISSUE TITLE
DEV-  Panic error on hibernating a deployment which doesn't exist

### ISSUE THREAD

**Issue by shri-astro** [astronomer/astro-cli#1570]
With no deployments in the workspace when the hibernate command is applied the panic error as follows is seen
```
shrividyahegde@Hegde ~ % astro deployment hibernate
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x1d8 pc=0x10469ef60]

goroutine 1 [running]:
github.com/astronomer/astro-cli/cloud/deployment.glob..func9({_, _}, {_, _, _, _}, {_, _})
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:1484 +0x140
github.com/astronomer/astro-cli/cloud/deployment.Create({0x0, _}, {_, _}, {_, _}, {_, _}, {_, _}, ...)
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:218 +0x29c
github.com/astronomer/astro-cli/cloud/deployment.deploymentSelectionProcess({_, _}, {_, _, _}, _, {_, _}, {_, _})
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:1672 +0x224
github.com/astronomer/astro-cli/cloud/deployment.GetDeployment({_, _}, {_, _}, {_, _}, _, _, {_, _}, ...)
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:1626 +0x1d4
github.com/astronomer/astro-cli/cloud/deployment.UpdateDeploymentHibernationOverride({0x0?, 0x0?}, {0x14000047d40, 0x19}, {0x0?, 0x0?}, 0x1, 0x0?, 0x0, {0x105297210, ...})
	/go/src/github.com/astronomer/astro-cli/cloud/deployment/deployment.go:1193 +0xc0
github.com/astronomer/astro-cli/cmd/cloud.deploymentOverrideHibernation(0x140000c0300, {0x105c337a0, 0x0, 0x0?}, 0x0?)
	/go/src/github.com/astronomer/astro-cli/cmd/cloud/deployment.go:850 +0x120
github.com/astronomer/astro-cli/cmd/cloud.newDeploymentHibernateCmd.func1(0x14000096300?, {0x105c337a0?, 0x4?, 0x104cda369?})
	/go/src/github.com/astronomer/astro-cli/cmd/cloud/deployment.go:558 +0x24
github.com/spf13/cobra.(*Command).execute(0x140000c0300, {0x105c337a0, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x66c
github.com/spf13/cobra.(*Command).ExecuteC(0x1400025a300)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(0x10528e6f8?)
	/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x1c
main.main()
	/go/src/github.com/astronomer/astro-cli/main.go:21 +0x38

```
**What CLI Version did you experience this bug?**
1.24.0

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro

**What Operating System is the above CLI installed on?**
Mac Pro M1

**Comment by kushalmalani** [comment]
This is released as part of 1.24.1
