### ISSUE TITLE
Airflow breaks after authenticating when using `astro dev start` 

### ISSUE THREAD

**Issue by FrikadelleHelle** [astronomer/astro-cli#1629]
**Describe the bug**

I am using the Astro CLI to boot airflow locally and get redirected to the login screen. But after 

The issue has also been created here: https://github.com/apache/airflow/issues/39170, but it seems to be a astro specific thing

```
2024-04-23 12:01:43 +0000] [84] [INFO] Listening at: http://0.0.0.0:8080 (84)
 [2024-04-23 12:01:43 +0000] [84] [INFO] Using worker: sync
 [2024-04-23 12:01:43 +0000] [111] [INFO] Booting worker with pid: 111
 [2024-04-23 12:01:43 +0000] [112] [INFO] Booting worker with pid: 112
 [2024-04-23 12:01:43 +0000] [113] [INFO] Booting worker with pid: 113
 [2024-04-23 12:01:43 +0000] [114] [INFO] Booting worker with pid: 114
 172.18.0.5 - - [23/Apr/2024:12:01:44 +0000] "GET /health HTTP/1.1" 200 318 "-" "curl/7.74.0"
 172.18.0.1 - - [23/Apr/2024:12:01:46 +0000] "GET / HTTP/1.1" 302 197 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.5 - - [23/Apr/2024:12:01:46 +0000] "GET /health HTTP/1.1" 200 318 "-" "curl/7.74.0"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /home HTTP/1.1" 302 285 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome HTTP/1.1" 200 19167 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/appbuilder/css/fontawesome/fontawesome.min.css HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/appbuilder/css/fontawesome/v4-shims.min.css HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/appbuilder/css/bootstrap.min.css HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/appbuilder/css/fontawesome/brands.min.css HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/appbuilder/css/bootstrap-datepicker/bootstrap-datepicker3.min.css HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/appbuilder/css/select2/select2.min.css HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/appbuilder/css/flags/flags16.css HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/appbuilder/css/select2/select2-bootstrap.min.css HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/appbuilder/css/ab.css HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/dist/loadingDots.84963375c34df3f17aab.css HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/dist/airflowDefaultTheme.c93fb34380b84747e945.css HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/dist/main.6f9728400381098372e3.css HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/appbuilder/css/fontawesome/regular.min.css HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/dist/bootstrap-datetimepicker.min.css HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /astro/static/update-notice.css HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/appbuilder/js/ab_actions.js HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/appbuilder/js/ab_filters.js HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/appbuilder/css/fontawesome/solid.min.css HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/dist/flash.39f43f5a4fffad4cd720.css HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /astro/static/update-notice.js HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/dist/materialIcons.ce0f77d10d4dc51f5f07.css HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/appbuilder/js/bootstrap.min.js HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/appbuilder/js/jquery-latest.js HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/appbuilder/js/bootstrap-datepicker/bootstrap-datepicker.min.js HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/dist/bootstrap-datetimepicker.min.js HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/dist/bootstrap3-typeahead.min.js HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/dist/main.6f9728400381098372e3.js HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/appbuilder/js/ab.js HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/dist/moment.0fcb6b41ff6a87cf079e.js HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/appbuilder/js/select2/select2.min.js HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/appbuilder/css/webfonts/fa-regular-400.5da313b0467f7c1b18d9.woff2 HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.1 - - [23/Apr/2024:12:01:47 +0000] "GET /static/appbuilder/css/webfonts/fa-solid-900.8f06540fd77f1effe1e2.woff2 HTTP/1.1" 304 0 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.5 - - [23/Apr/2024:12:01:49 +0000] "GET /health HTTP/1.1" 200 318 "-" "curl/7.74.0"
 172.18.0.5 - - [23/Apr/2024:12:01:51 +0000] "GET /health HTTP/1.1" 200 318 "-" "curl/7.74.0"
 [2024-04-23T12:01:52.602+0000] {override.py:1597} INFO - Updated user admin user
 172.18.0.1 - - [23/Apr/2024:12:01:52 +0000] "POST /login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome HTTP/1.1" 302 239 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 [2024-04-23T12:01:53.023+0000] {app.py:1744} ERROR - Exception on /home [GET]
 Traceback (most recent call last):
   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
     response = self.full_dispatch_request()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
     rv = self.handle_user_exception(e)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
     rv = self.dispatch_request()
          ^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/airflow/www/auth.py", line 139, in decorated
     return _has_access(
            ^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/airflow/www/auth.py", line 163, in _has_access
     return func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/airflow/www/views.py", line 1038, in index
     return self.render_template(
            ^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/airflow/www/views.py", line 714, in render_template
     return super().render_template(
            ^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/flask_appbuilder/baseviews.py", line 342, in render_template
     return render_template(
            ^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 147, in render_template
     return _render(app, template, context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/flask/templating.py", line 130, in _render
     rv = template.render(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
     self.environment.handle_exception()
   File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
     raise rewrite_traceback_stack(source=source)
   File "/usr/local/lib/python3.11/site-packages/airflow/www/templates/airflow/dags.html", line 44, in top-level template code
     {% elif curr_ordering_direction == 'asc' and request.args.get('sorting_key') == attribute_name %}
     ^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/astronomer/runtime/templates/runtime_base.html", line 1, in top-level template code
     {% extends original_base_template %}
     ^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/astronomer/airflow/version_check/templates/astro-baselayout.html", line 1, in top-level template code
     {% extends airflow_base_template %}
     ^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/airflow/www/templates/airflow/main.html", line 21, in top-level template code
     {% from 'airflow/_messages.html' import show_message %}
     ^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 2, in top-level template code
     {% import 'appbuilder/baselib.html' as baselib %}
     ^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/flask_appbuilder/templates/appbuilder/init.html", line 42, in top-level template code
     {% block body %}
   File "/usr/local/lib/python3.11/site-packages/flask_appbuilder/templates/appbuilder/baselayout.html", line 16, in block 'body'
     {% block messages %}
   File "/usr/local/lib/python3.11/site-packages/airflow/www/templates/airflow/dags.html", line 108, in block 'messages'
     {{ super() }}
   File "/usr/local/lib/python3.11/site-packages/astronomer/airflow/version_check/templates/astro-baselayout.html", line 3, in block 'messages'
     {% include "update-available.html" %}
     ^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/astronomer/airflow/version_check/templates/update-available.html", line 4, in top-level template code
     {% if "can_dismiss" | is_item_visible("UpdateAvailable") %}
     ^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/flask_appbuilder/filters.py", line 171, in is_item_visible
     return self.security_manager.has_access(permission_name, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/airflow/www/security_manager.py", line 142, in has_access
     return is_authorized_method(action_name, resource_pk, user)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/airflow/www/security_manager.py", line 340, in <lambda>
     method=get_method_from_fab_action_map()[action],
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
 KeyError: 'can_dismiss'
 172.18.0.1 - - [23/Apr/2024:12:01:53 +0000] "GET /home HTTP/1.1" 500 1593 "http://localhost:8080/login/?next=http%3A%2F%2Flocalhost%3A8080%2Fhome" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15"
 172.18.0.5 - - [23/Apr/2024:12:01:53 +0000] "GET /health HTTP/1.1" 200 318 "-" "curl/7.74.0"
 172.18.0.5 - - [23/Apr/2024:12:01:55 +0000] "GET /health HTTP/1.1" 200 318 "-" "curl/7.74.0"
```

**What CLI Version did you experience this bug?**

**This CLI bug is related to which Astronomer Platform?**

- [ ] Astro
- [ ] Software
- [ ] None/Unknown

**What Operating System is the above CLI installed on?**
macOS Sonoma 14.2.1 (23C71)

**🪜 Steps To Reproduce**

1. Run `astro dev start`
2. Wait for it open a browser
3. type `admin:admin`
4. get this error screen

<img width="1069" alt="image" src="https://github.com/astronomer/astro-cli/assets/146743279/eb59782b-1240-47c9-b055-784b45a638ec">

**Comment by rahulsain** [comment]
Same issue, any possible solution to this?

**Comment by BradleyOwenThompson** [comment]
I encountered the same issue yesterday using astro runtime 11.0.0. Upgrading to 11.1.0 appeared to fix the issue.

**Comment by FrikadelleHelle** [comment]
Only upgrading to runtime 11.1.0 worked for me. Wasn't sure what was meant at first, as im new to our astro deployment, so for anyone in same boat:

I went to the Dockerfile in the project and changed the image tag to 
`FROM quay.io/astronomer/astro-runtime:11.1.0`

I guess that its just a workaround still

**Comment by JarroVGIT** [comment]
What @keithbentrup says seems correct, and this issue has started in runtime 11.0.0. As of now, you can no longer run a local instance of Astro if you are not on the last runtime release when you use major version 11.

**Comment by TJaniF** [comment]
Hi :) 

This is likely related to this issue: https://github.com/apache/airflow/issues/39144 (which will be fixed in Airflow 2.9.1)

As a workaround you can either set `AIRFLOW__ASTRONOMER__UPDATE_CHECK_INTERVAL=0` or, since the issue only occurs if there is a newer Runtime version, use version 11.2.0.

**Comment by VRBradley** [comment]
encountering with 11.2.0 as of yesterday

**Comment by TJaniF** [comment]
> encountering with 11.2.0 as of yesterday

Yes, the issue is with custom plugin code that runs when a new version exists. It was now fixed in 11.3.0 and wont occur on 11.3.0 or later. :)

**Comment by franckishemezwe-plb** [comment]
I confirmed, I had the same issue and  I upgrade the runtime from 11.2.0 to 11.3.0 as suggested. Problem solved

**Comment by rajukrishnamurthy** [comment]
2.9.1/11.3 has been working for us too, however, as of today it stopped working.  I noticed that 11.4 was released today, I'm not sure if this is related.

**Comment by TJaniF** [comment]
> 2.9.1/11.3 has been working for us too, however, as of today it stopped working. I noticed that 11.4 was released today, I'm not sure if this is related.

Hi! I think that is could be a separate issue. I just tested 11.3.0 on a fresh, empty Astro CLI project and am not getting any errors. 
https://github.com/apache/airflow/pull/39167 and https://github.com/apache/airflow/pull/39421 should have fixed this, though you might have found an edge case.

Can you please file a new issue with some additional information about your set up? :)

**Comment by rajukrishnamurthy** [comment]
The underlying issue does not appear to be fixed and setting `AIRFLOW__ASTRONOMER__UPDATE_CHECK_INTERVAL=0` still works as a workaround.

**Comment by rajukrishnamurthy** [comment]
@jedcunningham we use bazel as our build system and we have a custom macro that creates the image, so there's not a dockerfile and an minimal example is going to be hard to create.  I'm assuming that needing update_check_interval means that we have some older dependency that doesn't contain the two fix, let me check that and I'll report back.

**Comment by jedcunningham** [comment]
@rajukrishnamurthy can you run `pip freeze | grep apache-airflow` in your image? 2 packages matter here afaik, `apache-airflow-providers-fab>=1.1.0` and `apache-airflow>=2.9.1+astro.1`.

**Comment by shlomiken** [comment]
This is still happening with 11.13, (with docker-compose not astro cli) 
here is the provider list we have on this image 
```
 docker run --rm airflow pip freeze | grep apache-airflow 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
apache-airflow==2.9.3+astro.7
apache-airflow-providers-amazon==8.20.0
apache-airflow-providers-apache-kafka==1.3.1
apache-airflow-providers-celery==3.8.3
apache-airflow-providers-cncf-kubernetes==8.4.2
apache-airflow-providers-common-compat==1.2.1
apache-airflow-providers-common-io==1.3.1
apache-airflow-providers-common-sql==1.12.0
apache-airflow-providers-databricks==6.3.0
apache-airflow-providers-datadog==3.5.1
apache-airflow-providers-elasticsearch==5.5.2
apache-airflow-providers-fab==1.0.4
apache-airflow-providers-ftp==3.8.0
apache-airflow-providers-google==10.17.0
apache-airflow-providers-http==4.10.1
apache-airflow-providers-imap==3.5.0
apache-airflow-providers-jenkins==3.5.1
apache-airflow-providers-mysql==5.6.0
apache-airflow-providers-postgres==5.13.1
apache-airflow-providers-redis==3.8.0
apache-airflow-providers-salesforce==5.6.3
apache-airflow-providers-slack==8.6.2
apache-airflow-providers-smtp==1.6.1
apache-airflow-providers-snowflake==5.4.0
apache-airflow-providers-sqlite==3.7.1

```
