### ISSUE TITLE
Clean up astro config

### ISSUE THREAD

**Issue by schnie** [astronomer/astro-cli#180]
`astro config` should throw a cleaner message when you don't input any deployments. It should also be a little clearer what kind of inputs this command needs.

```
virajparekh@orbiter:~$ astro config
Manage astro project configurations

Usage:
  astro config [command]

Available Commands:
  get         Get astro project configuration
  set         Set astro project configuration

Flags:
  -g, --global   view or modify global config
  -h, --help     help for config

Use "astro config [command] --help" for more information about a command.
virajparekh@orbiter:~$ astro config get
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/astronomer/astro-cli/cmd.ensureGlobalFlag(0x100b700, 0x106ce08, 0x0, 0x0)
	/go/src/github.com/astronomer/astro-cli/cmd/config.go:56 +0x218
github.com/astronomer/astro-cli/vendor/github.com/spf13/cobra.(*Command).execute(0x100b700, 0x106ce08, 0x0, 0x0, 0x100b700, 0x106ce08)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/spf13/cobra/command.go:682 +0x23c
github.com/astronomer/astro-cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x100ca20, 0x0, 0x100df60, 0xc4202a3f68)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/astronomer/astro-cli/vendor/github.com/spf13/cobra.(*Command).Execute(0x100ca20, 0xc4202a3f78, 0xc4200a0058)
	/go/src/github.com/astronomer/astro-cli/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
	/go/src/github.com/astronomer/astro-cli/main.go:10 +0x2d
```

**Comment by andriisoldatenko** [comment]
I removed `rm -rf .astro` and `rm -rf ~/.astro`

**Comment by vparekh94** [comment]
@andriisoldatenko what do you get if you run:

```
astro config get
```

**Comment by andriisoldatenko** [comment]
```
 go run main.go config get
Error: Must specify config key

Usage:
  astro config get [flags]

Flags:
  -h, --help   help for get

Global Flags:
  -g, --global   view or modify global config

2019/03/07 18:50:41 Must specify config key
exit status 1
```
@vparekh94

**Comment by schnie** [comment]
This seems to work fine for me as well. @vparekh94 open back up if you experience this again.
