### ISSUE TITLE
Clean up error message on deprecated commands

### ISSUE THREAD

**Issue by schnie** [astronomer/astro-cli#264]
We currently show a message when we run an old version of a command, but we also show the stack trace. We should hide the stack trace. Ex:

```
astro airflow deploy
Command "deploy" is deprecated, Please use new command instead `astro deploy DEPLOYMENT [flags]`
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9daac2]

goroutine 1 [running]:
github.com/astronomer/astro-cli/cmd.glob..func1(0x1124b00, 0x1159e40, 0x0, 0x0)
        /go/src/github.com/astronomer/astro-cli/cmd/airflow.go:69 +0x52
github.com/astronomer/astro-cli/vendor/github.com/spf13/cobra.(*Command).execute(0x1124b00, 0x1159e40, 0x0, 0x0, 0x1124b00, 0x1159e40)
        /go/src/github.com/astronomer/astro-cli/vendor/github.com/spf13/cobra/command.go:830 +0x2ae
github.com/astronomer/astro-cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1128e80, 0x9db297, 0xc0001f3f88, 0xc0000300b8)
        /go/src/github.com/astronomer/astro-cli/vendor/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/astronomer/astro-cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/astronomer/astro-cli/vendor/github.com/spf13/cobra/command.go:864
main.main()
        /go/src/github.com/astronomer/astro-cli/main.go:10 +0x2e
```

**Comment by andriisoldatenko** [comment]
https://github.com/astronomer/astro-cli/pull/265
