### ISSUE TITLE
Error while astro deploy in Github Actions for DEV env

### ISSUE THREAD

**Issue by dsgupta02** [astronomer/astro-cli#830]
**Describe the bug**
Getting error while deploying dags in github-sync in Dev Env

1. Run below set of command in github

```
curl -sSL https://install.astronomer.io/ | sudo bash -s v1.7.0
astro context switch astronomer-dev.io
astro deploy
```
Result :
```
CONTEXT DOMAIN                      WORKSPACE                           
 astronomer-dev.io                                                       

 Switched context
Using an Astro API key
 CONTEXT DOMAIN                      WORKSPACE                           
 astronomer.io                                                           

 Switched context
2022/10/21 16:04:09 API error (400): {"error":"invalid_request","error_description":"Invalid domain 'auth.astronomer.io' for client_id '***'"}
Error: Process completed with exit code 1.
````

2. Also tried this 
```
curl -sSL https://install.astronomer.io/ | sudo bash -s v1.7.0
astro context delete astronomer.io
astro deploy
```
Result :
```
astronomer/astro-cli info checking GitHub for tag 'v1.7.0'
astronomer/astro-cli info found version: 1.7.0 for v1.7.0/linux/amd64
astronomer/astro-cli info installed /usr/local/bin/astro
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/astronomer/astro-cli/config.(*Context).DeleteContext(0x0?)
	/go/src/github.com/astronomer/astro-cli/config/context.go:193 +0x12c
github.com/astronomer/astro-cli/context.Delete({0x7fff59122f6f, 0xd}, 0x0)
	/go/src/github.com/astronomer/astro-cli/context/context.go:92 +0x258
github.com/astronomer/astro-cli/context.DeleteContext(...)
	/go/src/github.com/astronomer/astro-cli/context/context.go:153
github.com/astronomer/astro-cli/cmd.newContextDeleteCmd.func1(0xc0002b5b80?, {0xc00030ff10?, 0x1?, 0x1?})
	/go/src/github.com/astronomer/astro-cli/cmd/context.go:60 +0x3a
github.com/spf13/cobra.(*Command).execute(0xc0002b5b80, {0xc00030fef0, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002b2000)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	/go/src/github.com/astronomer/astro-cli/main.go:16 +0x31
Error: Process completed with exit code 2.
```

**What CLI Version did you experience this bug?**

1.7.0

**📸 Screenshots**

<img width="1049" alt="Screenshot 2022-10-21 at 11 06 13 PM" src="https://user-images.githubusercontent.com/100349882/197255847-60be8275-c5e2-4c37-907e-0bba3f780ee3.png">

**Comment by sunkickr** [comment]
related PR https://github.com/astronomer/astro-cli/pull/839
