### ISSUE TITLE
E2E on Dev failing on "Runs astro deployment worker-queue update"

### ISSUE THREAD

**Issue by nkapinos** [astronomer/astro-cli#845]
**Describe the bug**

The Dev E2E CLI test is failing with error below.

```
Deployment Commands after login, deployment create, and dev init
    ✓ Runs "astro deploy" (409060ms)
    ✓ Runs "astro deployment list" (1025ms)
    ✓ Runs "astro deployment update" (8089ms)
    ✓ Runs "astro deployment logs" (1929ms)
    worker queue
      1) "before all" hook for "Runs astro deployment worker-queue update""
        cy:command ✘  exec	astro deployment worke...


      2) "after all" hook for "Runs astro deployment worker-queue update""
        cy:command ✘  exec	astro deployment worke...



cypress-terminal-report: Wrote custom logs to logs. (73ms)

  4 passing (9m)
  2 failing

  1) Deployment Commands after login, deployment create, and dev init
       worker queue
         "before all" hook for "Runs astro deployment worker-queue update"":
     CypressError: `cy.exec('astro deployment worker-queue create
  -n e2e-ci-main-wq-gekt3
  -d cl9sh0g9e2292761kzo0jym84mf
  -t m5.xlarge')` timed out after waiting `60000ms`.

https://on.cypress.io/exec

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `worker queue`

Although you have test retries enabled, we do not retry tests when `before all` or `after all` hooks fail
      at https://cloud.astronomer-dev.io/__cypress/runner/cypress_runner.js:140075:85
      at tryCatcher (https://cloud.astronomer-dev.io/__cypress/runner/cypress_runner.js:11318:23)
```

**What CLI Version did you experience this bug?**

This is running on the dev version of CLI (local build)

**What Operating System is the above CLI installed on?**

**🪜 Steps To Reproduce**

1.  Visit circleci job: https://app.circleci.com/pipelines/github/astronomer/astro/30817/workflows/6e60eaee-f331-4067-bd39-f391be39132c/jobs/728547

**📸 Screenshots**

**Comment by jemishp** [comment]
@nkapinos the error is when the test ran astro deployment worker-queue create
  -n e2e-ci-main-wq-gekt3
  -d cl9sh0g9e2292761kzo0jym84mf
  -t m5.xlarge')` timed out after waiting `60000ms`.

**Comment by jemishp** [comment]
fixed.
